Make major changes of the HTML and CSS file.
katarighe/my-portfolio pull request #3
Opened 2023-06-02 15:16 UTC by katarighe

Made major changes to the HTML and CSS file of the portfolio project and finished the mobile version of the project. 

1) Added the works and abous me section of the portfolio.

2) Used Flexbox and CSS grid to place the elements of the page. 

3) Added list items in the Work and About Myself section. 

4) The current design is compiled according to Figma. 

![image](https://github.com/katarighe/my-portfolio/assets/80690364/703758f2-d8b6-4fed-869c-5b9bc793c884)
![image](https://github.com/katarighe/my-portfolio/assets/80690364/665c56a2-f599-4383-83d9-bf03b856d171)

2023-06-02 16:14 UTC, divinecharlotte requested changes
Hi @katarighe         , 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## To Highlight 💯 
- Descriptive commit messages 👍 
- Linters are passing 👍 
 




 
![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)
## Required Changes ♻️
 ☠️ Next time consider opening a pr on a branch that contains all your work to make the review process smooth and for you to easily understand why a required change cause that will allow a reviewer to highlight the code which requires change 

- [x] kindly consider adding a working link to your Twitter  and LinkedIn account under the author's section to give a good user experience to the people visiting your readme

- [ ] Kindly consider adding the technology categories ("Languages", "Frameworks" and "Skills") in a `ul`, each of them in a `li` because they are also a list and remember `ul` and `li` are used to represent an item in a list 😃 
_Check the comments under the review._
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-02 17:05 UTC, katarighe commented on index.html
>    </div>
@divinecharlotte Also, I am confused in this section. 😕😵

2023-06-02 17:07 UTC, katarighe commented on index.html
>  <section id="works">
@divinecharlotte Can you give me an example, according to your perspective, 

Here is my sample work, what should I change according to your comments, from the HTML and CSS file. 

I'm currently struggling, also confused. Here is my sample: 

<section id="works">
  <div class="works_card">
    <img src="./images/SnapshootPortfolio.svg" alt="SnapshootPortfolio">
    <div class="works_card_detail">
      <div class="works_card_title">
        <h2>Tonic</h2>
        <div class="works_card_history">
          <div class="works_card_history_detail"><p>CANOPY</p></div>
          <div><img src="./images/Counter.svg" alt=""></div>
          <div class="works_card_history_detail"><p>Back End Dev</p></div>
          <div><img src="./images/Counter.svg" alt=""></div>
          <div class="works_card_history_detail"><p>2015</p></div>
        </div>

2023-06-03 12:04 UTC, aamirkhan2478 requested changes
Hi @katarighe, 

![](https://media3.giphy.com/media/RcZlXVml8oKtoGQeqe/giphy.gif?cid=ecf05e47cw5pjd1gapdzk1t3vp0n73caujoqxw3vkcu8ssng&rid=giphy.gif&ct=g)

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

 ## Highlights
✔️ Good Effort
✔️ Your design is good.
✔️ All linters passed

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-03 12:04 UTC, aamirkhan2478 commented on index.html
https://github.com/katarighe/my-portfolio/blob/826a56ad2ccb9c1fae1161903ef5170e758ee978/index.html#L200-L206

[OPTIONAL] This is optional but recommended because this is missed by the previous reviewer :point_up_2: that's why it's optional so kindly don't skip it please fix your some social media icons it's not shown :+1: check below :point_down: your design :slightly_smiling_face: 

![Screenshot from 2023-06-03 16-55-00](https://github.com/katarighe/my-portfolio/assets/45226848/86dcdbb2-95ec-4c1e-8440-eb2a3a11cd8f)

2023-06-03 13:18 UTC, merged